name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Analyze directory contents
      run: |
        echo "Directory contents with sizes:"
        du -sh * | sort -rh | head -n 20
        echo "Total size:"
        du -sh .

    - name: Clean up artifacts
      run: |
        find . -type d -name "__pycache__" -exec rm -rf {} +
        find . -type f -name "*.pyc" -delete

    - name: Create deployment package
      run: |
        zip -r deploy.zip . -i "*.py" "*.txt" "*.html" "*.css" "*.js" "requirements.txt" "runtime.txt" "startup.txt"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myLMS-new'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy.zip
      timeout-minutes: 30

    - name: Verify deployment
      run: |
        echo "Deployment completed. Check Azure portal for details."