name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Analyze directory contents
      run: |
        echo "Directory contents with sizes:"
        du -sh * | sort -rh | head -n 20
        echo "Total size:"
        du -sh .

    - name: Clean up artifacts
      run: |
        find . -type d -name "__pycache__" -exec rm -rf {} +
        find . -type f -name "*.pyc" -delete

    - name: Print crucial file contents
      run: |
        echo "runtime.txt:"
        cat runtime.txt
        echo "requirements.txt:"
        cat requirements.txt
        echo "startup.txt:"
        cat startup.txt
        echo "mylms/settings.py (partial):"
        grep -n "ALLOWED_HOSTS\|DEBUG" mylms/settings.py

    - name: Update startup.txt and add web.config
      run: |
        echo "gunicorn --bind=0.0.0.0 --timeout 600 mylms.wsgi:application" > startup.txt
        echo '<?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
            </handlers>
            <httpPlatform processPath="python" arguments="%home%\site\wwwroot\startup.txt" requestTimeout="00:04:00" startupTimeLimit="120" startupRetryCount="3" stdoutLogEnabled="true">
              <environmentVariables>
                <environmentVariable name="PYTHONPATH" value="%home%\site\wwwroot"/>
              </environmentVariables>
            </httpPlatform>
          </system.webServer>
        </configuration>' > web.config

    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" "*.pyc" "__pycache__/*" "node_modules/*" "venv/*"

    - name: Print deployment package contents
      run: unzip -l deploy.zip

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myLMS-new'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy.zip

    - name: Verify deployment
      run: |
        echo "Deployment completed. Check Azure portal for details."